name: Zip and Upload Release

on:
  workflow_dispatch:

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Read version from manifest.json
      id: version
      run: |
        VERSION=$(jq -r '.version' manifest.json)
        echo "VERSION_TAG=v$VERSION" >> $GITHUB_ENV
        echo "::set-output name=tag::v$VERSION"

    - name: Create ZIP archive
      run: |
        zip -r hku-gym-booker.zip . -x "*.git*" -x ".*" -x "assets/*"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: Release ${{ steps.version.outputs.tag }}
        files: hku-gym-booker.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
